name: cha_bap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+49

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  bootpay: ^4.3.4
  bootpay_webview_flutter: ^3.2.21
  built_collection: 5.1.1
  built_value: 8.4.3
  cached_network_image: 3.2.1
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  crypto: ^3.0.2
  dio: ^4.0.6
  easy_debounce: 2.0.1
  encrypt: ^5.0.1
  equatable: 2.0.3
  firebase_auth: ^4.4.1
  firebase_auth_platform_interface: ^6.13.0
  firebase_auth_web: ^5.3.1
  firebase_core: ^2.9.0
  firebase_core_platform_interface: ^4.6.0
  firebase_core_web: ^2.3.0
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_facebook_auth: 
    git:
      url: https://github.com/asmengistu/flutter-facebook-auth
      ref: b65ffb049c9f1e2704adbeb1aa19c61693c946a5
      path: facebook_auth
  fluttertoast: ^8.0.9
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  geolocator: 9.0.1
  geolocator_android: 4.1.0
  geolocator_apple: 2.2.1
  geolocator_platform_interface: 4.0.6
  geolocator_web: 2.1.6
  get: ^4.6.5
  google_fonts: 4.0.3
  google_maps: 6.2.0
  google_maps_flutter: 2.1.8
  google_maps_flutter_platform_interface: 2.2.1
  google_maps_flutter_web: 0.4.0+1
  google_sign_in: 5.4.0
  google_sign_in_ios: 5.4.0
  google_sign_in_platform_interface: 2.2.0
  google_sign_in_web: 0.10.2
  http: ^0.13.5
  intl: 0.17.0
  js: ^0.6.4
  json_annotation: ^4.8.0
  json_path: 0.4.1
  json_serializable: 6.6.1
  kakao_flutter_sdk_common: ^1.4.2
  kakao_flutter_sdk_navi: ^1.4.2
  kakao_flutter_sdk_user: ^1.4.2
  lottie: 1.2.1
  mime_type: 1.0.0
  package_info: ^2.0.2
  page_transition: 2.0.4
  pin_code_fields: 7.4.0
  platform: ^3.1.0
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  rxdart: 0.27.5
  shared_preferences: ^2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sign_in_with_apple: 4.1.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  stream_channel: ^2.1.1
  timeago: 3.2.2
  url_launcher: 6.1.10
  uuid: ^3.0.6
  web_socket_channel: ^2.3.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: 2.3.3
  built_value_generator: 8.4.3
  flutter_launcher_icons: 0.12.0

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: 'AppleGothicSDNeo'
      fonts:
        - asset: assets/fonts/AppleSDGothicNeoT.ttf
          weight: 100
        - asset: assets/fonts/AppleSDGothicNeoUL.ttf
          weight: 200
        - asset: assets/fonts/AppleSDGothicNeoL.ttf
          weight: 300
        - asset: assets/fonts/AppleSDGothicNeoR.ttf
        - asset: assets/fonts/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: assets/fonts/AppleSDGothicNeoSB.ttf
          weight: 600
        - asset: assets/fonts/AppleSDGothicNeoB.ttf
          weight: 700
        - asset: assets/fonts/AppleSDGothicNeoEB.ttf
          weight: 800


    - family: IconRegistration
      fonts:
        - asset: assets/fonts/icon_registration.ttf
    - family: IconNavibar
      fonts:
        - asset: assets/fonts/icon_navibar.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
